### ISSUE TITLE
请问为何私钥加密padding不可以是RSA_PKCS1_OAEP_PADDING

### ISSUE THREAD

**Issue by xiaoxin1** [wensenl/lua-resty-rsa#1]
公钥加密支持，求问。。

**Comment by wensenl** [comment]
man RSA_private_encrypt

**Comment by wensenl** [comment]
私钥加密，公钥解密是不支持RSA_PKCS1_OAEP_PADDING；只有是公钥加密，私钥解密才支持RSA_PKCS1_OAEP_PADDING；具体可以查看帮助man RSA_private_encrypt。
